 $(function() {
		 var availableSchools = [
				 "Harvard University",
         "Amherst College",
         "Arizona State University",
         "Australian National University",
         "Barnard College",
         "Bates College",
         "Binghamton University SUNY",
         "Boston College",
         "Boston University",
         "Bowdoin College",
         "Brandeis University",
         "Brown University",
         "Bryn Mawr College",
         "California Institute of Technology",
         "Carleton College",
         "Carnegie Mellon University",
         "Case Western Reserve University",
         "Charité Universitätsmedizin Berlin",
         "Chinese University of Hong Kong",
         "City University of Hong Kong",
         "Claremont McKenna College",
         "Clemson University",
         "Colgate University",
         "Columbia University",
         "Cornell University",
         "Dartmouth College",
         "Davidson College",
         "Delft University of Technology",
         "Drexel University",
         "Duke University",
         "École Polytechnique Fédérale de Lausanne",
         "Emory University",
         "Erasmus University Rotterdam",
         "ETH Zurich",
         "Florida State University",
         "Fordham University",
         "Fudan University",
         "George Washington University",
         "Georgetown University",
         "Georgia Institute of Technology",
         "Grinnell College",
         "Hamilton College",
         "Harvard University",
         "Haverford College",
         "Heidelberg University",
         "Imperial College London",
         "Indiana University",
         "Institut Polytechnique de Paris",
         "Johns Hopkins University",
         "Karolinska Institute",
         "King's College",
         "Korea Advanced Institute of Science and Technology",
         "Korea University",
         "KU Leuven",
         "Kyoto University",
         "Lafayette College",
         "Lehigh University",
         "Leiden University",
         "LMU Munich",
         "London School of Economics and Political Science",
         "Loyola Marymount University",
         "Ludwig Maximilians Universität München",
         "Massachusetts Institute of Technology",
         "McGill University",
         "McMaster University",
         "Michigan State University",
         "Middlebury College",
         "Monash University",
         "Mount Holyoke College",
         "Nanyang Technological University, Singapore",
         "National Taiwan University",
         "National University of Singapore",
         "New York University",
         "North Carolina State University",
         "Northeastern University",
         "Northwestern University",
         "Ohio State University",
         "Osaka University",
         "Paris Sciences et Lettres PSL Research University Paris",
         "Peking University",
         "Pennsylvania State University",
         "Pepperdine University",
         "Pomona College",
         "Princeton University",
         "Purdue University",
         "Rensselaer Polytechnic Institute",
         "Rice University",
         "Ruprecht-Karls-Universität Heidelberg",
         "Rutgers University",
         "Santa Clara University",
         "Scripps College",
         "Seoul National University",
         "Shanghai Jiao Tong University",
         "Smith College",
         "Sorbonne University",
         "Southern Methodist University",
         "Stanford University",
         "Stony Brook University",
         "Swarthmore College",
         "Syracuse University",
         "Technical University of Munich",
         "Temple University",
         "Texas A&M University",
         "The Hong Kong Polytechnic University",
         "The Hong Kong University of Science and Technology",
         "The University of Arizona",
         "The University of Queensland",
         "Tokyo Institute of Technology",
         "Tsinghua University",
         "Tufts University",
         "Tulane University",
         "UCL",
         "Universidad de Buenos Aires",
         "Universiti Malaya",
         "University at Buffalo SUNY",
         "University of Amsterdam",
         "University of Bristol",
         "University of British Columbia",
         "University of California Berkeley",
         "University of California Davis",
         "University of California Irvine",
         "University of California Los Angeles",
         "University of California San Diego",
         "University of California Santa Barbara",
         "University of Cambridge",
         "University of Chicago",
         "University of Connecticut",
         "University of Edinburgh",
         "University of Florida",
         "University of Georgia",
         "University of Glasgow",
         "University of Hong Kong",
         "University of Houston",
         "University of Illinois",
         "University of Illinois at Chicago",
         "University of Manchester",
         "University of Maryland",
         "University of Massachusetts",
         "University of Melbourne",
         "University of Miami",
         "University of Michigan",
         "University of Minnesota",
         "University of Montreal",
         "University of New Mexico",
         "University of North Carolina",
         "University of Notre Dame",
         "University of Oxford",
         "University of Pennsylvania",
         "University of Pittsburgh",
         "University of Richmond",
         "University of Rochester",
         "University of Southern California",
         "University of Sydney",
         "University of Texas at Austin",
         "University of Tokyo",
         "University of Toronto",
         "University of Virginia",
         "University of Warwick",
         "University of Washington",
         "University of Wisconsin",
         "University of Zurich",
         "UNSW Sydney",
         "Vanderbilt University",
         "Vassar College",
         "Villanova University",
         "Virginia Polytechnic Institute and State University",
         "Virginia Tech",
         "Wageningen University & Research",
         "Wake Forest University",
         "Washington and Lee University",
         "Washington University in St Louis",
         "Washington University in St. Louis",
         "Wellesley College",
         "Wesleyan University",
         "William & Mary",
         "Williams College",
         "Worcester Polytechnic Institute",
         "Yale University",
         "Zhejiang University",

		 ];
		 $( "#schools" ).autocomplete({
				 source: availableSchools
		 });
 });
