schoolList = [
("ICL", ["Imperial Coll London", "Imperial Coll"]),
("KTH", ["Royal Inst Technol", "Royal Inst Technol KTH", "KTH Royal Inst Technol"]),
("LoyolaM", ["Loyola Marymount Univ"]),
("POSTECH", ["POSTECH", "Pohang Univ Sci & Technol"]),
("PSL", ["Ecole Normale Super", "PSL Univ"]),
("UCSB", ["Univ Calif Santa Barbara", "UC Santa Barbara"]),
("UCSF", ["Univ Calif San Francisco"]),
("UIUC", ["Univ Illinois", "Univ Illinois Urbana Champaign UIUC"]),
("UNC", ["Univ N Carolina"]),
("aarhus", ["Aarhus Univ"]),
("adelaide", ["Univ Adelaide"]),
("amsterdam", ["Univ Amsterdam"]),
("arizona", ["Univ Arizona"]),
("asu", ["Arizona State Univ"]),
("auckland", ["Univ Auckland"]),
("ausNational", ["Australian Natl Univ"]),
("barcelona", ["Univ Barcelona"]),
("basel", ["Univ Basel"]),
("berkeley", ["Univ Calif Berkeley"]),
("berlin", ["Charite"]),
("birmingham", ["Univ Birmingham"]),
("bonn", ["Rheinische Friedrich Wilhelms Univ Bonn", "Univ Bonn"]),
("bostonc", ["Boston Coll"]),
("bostonu", ["Boston Univ"]),
("boulder", ["Univ Colorado"]),
("brandeis", ["Brandeis Univ"]),
("bristol", ["Univ Bristol"]),
("brown", ["Brown Univ"]),
("buenosAires", ["Univ Buenos Aires"]),
("caltech", ["CALTECH"]),
("cambridge", ["Cambridge Judge Business Sch", "Univ Cambridge Darwin Coll", "Univ Cambridge", "Cambridge Ctr Adv Res & Educ Singapore CARES"]),
("caseWestern", ["Case Western Reserve Univ"]),
("chicago", ["Univ Chicago"]),
("cityHK", ["City Univ Hong Kong"]),
("cmu", ["Carnegie Mellon Univ"]),
("columbia", ["Columbia Univ", "Columbia Business Sch"]),
("cornell", ["Cornell Univ", "Cornell Law Sch"]),
("cuHK", ["Chinese Univ Hong Kong"]),
("dartmouth", ["Dartmouth Coll"]),
("davis", ["Univ Calif Davis"]),
("delft", ["Delft Univ Technol"]),
("drexel", ["Drexel Univ"]),
("duke", ["Duke Univ"]),
("durham", ["Univ Durham"]),
("edinburgh", ["Univ Edinburgh"]),
("emory", ["Emory Univ"]),
("erasmus", ["Erasmus Univ"]),
("florida", ["Univ Florida"]),
("fordham", ["Fordham Univ"]),
("freiburg", ["Univ Freiburg"]),
("fsu", ["Florida State Univ"]),
("fudan", ["Fudan Univ"]),
("geneva", ["Univ Geneva"]),
("georgetown", ["Georgetown Univ"]),
("georgiaTech", ["Georgia Inst Technol"]),
("ghent", ["Univ Ghent"]),
("glasgow", ["Univ Glasgow"]),
("groningen", ["Univ Groningen"]),
("gwu", ["George Washington Univ"]),
("harvard", ["Harvard Univ", "Harvard Med Sch"]),
("hebrewU", ["Hebrew Univ Jerusalem"]),
("helsinki", ["Univ Helsinki"]),
("hkPoly", ["Hong Kong Polytech Univ", "Hong Kong Polytech Univ Hung Hom"]),
("hkuScienceTech", ["Hong Kong Univ Sci & Technol", "HKUST"]),
("hongKong", ["Univ Hong Kong"]),
("hopkins", ["Johns Hopkins Univ", "Johns Hopkins Carey Business Sch", "Johns Hopkins Bloomberg Sch Publ Hlth", "Johns Hopkins Appl Phys Lab"]),
("houston", ["Univ Houston"]),
("huBerlin", ["Humboldt Univ", "Weizenbaum Inst Networked Soc"]),
("icahn", ["Icahn Sch Med Mt Sinai"]),
("irvine", ["Univ Calif Irvine"]),
("kaist", ["Korea Adv Inst Sci & Technol", "Korea Adv Inst Sci & Technol KAIST", "Korean Adv Inst Sci & Technol KAIST"]),
("karolinska", ["Karolinska Inst"]),
("kingAbdulaziz", ["King Abdulaziz Univ", "King Abdulaziz Univ KAU"]),
("kings", ["Kings Coll London"]),
("korea", ["Korea Univ"]),
("kyoto", ["Kyoto Univ"]),
("lausanne", ["Ecole Polytech Fed Lausanne"]),
("leeds", ["Univ Leeds"]),
("lehigh", ["Lehigh Univ"]),
("leiden", ["Leiden Univ"]),
("londonSE", ["London Sch Econ", "LSE", "London Sch Econ & Polit Sci"]),
("lund", ["Lund Univ"]),
("malaya", ["Univ Malaya"]),
("manchester", ["Univ Manchester"]),
("maryland", ["Univ Maryland"]),
("mcgill", ["McGill Univ"]),
("mcmaster", ["McMaster Univ"]),
("melbourne", ["Univ Melbourne"]),
("michigan", ["Univ Michigan"]),
("michiganState", ["Michigan State Univ"]),
("minnesota", ["Univ Minnesota"]),
("mit", ["MIT", "MIT & Harvard", "Stanford CodeX Blockchain Grp", "MIT Sloan Sch Management", "MIT Media Lab"]),
("monash", ["Monash Univ", "Monash Univ Malaysia"]),
("montreal", ["Univ Montreal"]),
("moscowState", ["Lomonosov Moscow State Univ", "Moscow MV Lomonosov State Univ"]),
("nagoya", ["Nagoya Univ"]),
("nanyang", ["Nanyang Technol Univ", "Nanyang Technol Univ NTU"]),
("national-taiwan", ["Natl Taiwan Univ"]),
("ncState", ["North Carolina State Univ"]),
("newMexico", ["Univ New Mexico"]),
("northeastern", ["Northeastern Univ"]),
("northwestern", ["Northwestern Univ", "Northwestern Pritzker Sch Law"]),
("notreDame", ["Univ Notre Dame"]),
("nus", ["Natl Univ Singapore", "NUS"]),
("nyu", ["NYU"]),
("ohioState", ["Ohio State Univ"]),
("osaka", ["Osaka Univ"]),
("oslo", ["Univ Oslo"]),
("oxford", ["Univ Oxford", "Oxford Internet Inst"]),
("peking", ["Peking Univ"]),
("penn", ["Univ Penn"]),
("pennState", ["Penn State Univ", "Penn State Behrend"]),
("pepperdine", ["Pepperdine Univ"]),
("pittsburgh", ["Univ Pittsburgh"]),
("polytechnique-paris", ["Ecole Polytech"]),
("princeton", ["Princeton Univ"]),
("purdue", ["Purdue Univ"]),
("queensland", ["Univ Queensland"]),
("rensselaer", ["Rensselaer Polytech Inst"]),
("rice", ["Rice Univ"]),
("rmit", ["RMIT Univ", "Royal Melbourne Inst Technol RMIT Univ"]),
("rochester", ["Univ Rochester"]),
("ruprechtKarls", ["Heidelberg Univ"]),
("rutgers", ["Rutgers State Univ", "Rutgers Business Sch Newark & New Brunswick", "Rutgers Business Sch"]),
("saclay", ["Paris Saclay Univ", "Univ Paris Saclay", "Paris Saclay"]),
("santaClara", ["Santa Clara Univ"]),
("seoulNational", ["Seoul Natl Univ", "Seoul Natl Univ Hosp", "SNU"]),
("shanghaiJT", ["Shanghai Jiao Tong Univ", "SJTU"]),
("sheffield", ["Univ Sheffield"]),
("skku", ["Sungkyunkwan Univ", "SungKyunKwan Univ"]),
("smith", ["Smith Coll"]),
("smu", ["Southern Methodist Univ"]),
("sorbonne", ["Sorbonne Univ"]),
("southampton", ["Univ Southampton"]),
("stAndrews", ["Univ St Andrews"]),
("stanford", ["Stanford Univ"]),
("stockholm", ["Stockholm Univ"]),
("stonyBrook", ["SUNY Stony Brook"]),
("sunYatSen", ["Sun Yat Sen Univ"]),
("suny-b", ["SUNY Binghamton", "Binghamton Univ"]),
("sunyBuffalo", ["SUNY Buffalo", "Univ Buffalo State Univ New York", "Univ Buffalo SUNY"]),
("sydney", ["Univ Sydney"]),
("syracuse", ["Syracuse Univ"]),
("technicalDenmark", ["Tech Univ Denmark"]),
("technicalMunich", ["Tech Univ Munich", "Tech Univ Munchen TUM"]),
("technion", ["Technion", "Technion IIT", "Technion Univ", "Technion Israel Inst Technol"]),
("temple", ["Temple Univ"]),
("texasAM", ["Texas A&M Univ"]),
("tohoku", ["Tohoku Univ"]),
("tokyoTech", ["Tokyo Inst Technol"]),
("toronto", ["Univ Toronto"]),
("tsinghua", ["Tsinghua Univ"]),
("tubingen", ["Univ Tubingen"]),
("tufts", ["Tufts Univ"]),
("tulane", ["Tulane Univ"]),
("uConn", ["Univ Connecticut"]),
("uCopenhagen", ["Univ Copenhagen"]),
("uGeorgia", ["Univ Georgia"]),
("uMass", ["Univ Massachusetts", "UMass Amherst", "Univ Massachusetts Amherst"]),
("uMiami", ["Univ Miami"]),
("uScienceTechChina", ["Univ Sci & Technol China", "USTC"]),
("uTokyo", ["Univ Tokyo"]),
("uZurich", ["Univ Zurich", "Univ Zurich UZH"]),
("ubc", ["Univ British Columbia"]),
("ucsc", ["Univ Calif Santa Cruz"]),
("uiChicago", ["Univ Illinois"]),
("unswSydney", ["Univ New South Wales", "UNSW Sydney", "Univ New South Wales Sydney", "UNSW", "Univ New South Wales UNSW"]),
("uparis", ["Univ Paris"]),
("uppsala", ["Uppsala Univ"]),
("usc", ["Univ Southern Calif"]),
("utAustin", ["Univ Texas Austin", "UT Austin"]),
("utrecht", ["Utrecht Univ UU", "Univ Utrecht"]),
("uva", ["Univ Virginia"]),
("vanderbilt", ["Vanderbilt Univ"]),
("villanova", ["Villanova Univ", "Villanova Law Sch"]),
("virginiaTech", ["Virginia Tech", "Virginia Polytech Inst & State Univ"]),
("vuAmsterdam", ["Vrije Univ Amsterdam", "Vrije Univ"]),
("wageningen", ["Wageningen Univ & Res", "Wageningen Res", "Wageningen Food Safety Res", "Wageningen Univ", "Wageningen Econ Res"]),
("wakeForest", ["Wake Forest Univ"]),
("weizmann", ["Weizmann Inst Sci"]),
("westernAus", ["Univ Western Australia", "UWA"]),
("williamMary", ["William & Mary"]),
("wisconsin", ["Univ Wisconsin"]),
("worcester", ["Worcester Polytech Inst"]),
("wustl", ["Washington Univ"]),
("yale", ["Yale Univ"]),
("yonsei", ["Yonsei Univ"]),
("zhejiang", ["Zhejiang Univ"])
]
